"""
fix_supabase_passwords.py — Force-reset password hashes for ALL seeded demo accounts.

This script connects to the database specified by DATABASE_URL and unconditionally
updates password_hash for ALL seeded customer and worker accounts to a fresh bcrypt hash.

WHY: The hashes stored in Supabase may have been generated by a different Python/bcrypt
version than what Render uses, causing verify_password() to return False even for a
correct password.

USAGE (PowerShell):
    $env:DATABASE_URL = "postgresql+psycopg://postgres.[REF]:[PASSWORD]@aws-0-[REGION].pooler.supabase.com:6543/postgres"
    cd backend
    python fix_supabase_passwords.py

DOES NOT:
- Print the password or any hashes
- Drop or alter any tables
- Change any data other than password_hash
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

DEMO_PASSWORD = "Password123!"

SEEDED_CUSTOMER_EMAILS = [
    "customer@example.com",
    "rahul.verma@example.com",
    "ananya.sharma@example.com",
    "priya.patel@example.com",
    "amit.singh@example.com",
    "vikram.joshi@example.com",
    "sunita.rao@example.com",
    "deepak.gupta@example.com",
    "neha.tiwari@example.com",
    "rohit.mehta@example.com",
]

SEEDED_WORKER_EMAILS = [
    "worker@example.com",
    "suresh.kumar@example.com",
    "ramesh.patel@example.com",
    "dinesh.yadav@example.com",
    "manoj.tiwari@example.com",
    "anita.devi@example.com",
    "ramu.lal@example.com",
    "vijay.verma@example.com",
    "santosh.mishra@example.com",
    "jagdish.prasad@example.com",
    "arvind.gupta@example.com",
    "vikas.c@example.com",
    "sanjay.soni@example.com",
    "pappu.lodhi@example.com",
    "kamlesh.sen@example.com",
    "sunita.bai@example.com",
    "mohan.sahu@example.com",
    "anil.v@example.com",
    "rakesh.dubey@example.com",
    "pradeep.sen@example.com",
]


def main():
    print("=" * 58)
    print("  Sahayu Supabase Password Fix Utility")
    print("=" * 58)

    db_url = os.environ.get("DATABASE_URL", "")
    if not db_url:
        print("[FAIL] DATABASE_URL is not set. Aborting.")
        sys.exit(1)

    print(f"[OK]   DATABASE_URL is set (redacted)")

    try:
        from app.database import SessionLocal
        from app.models import CustomerData, WorkerData
        from app.core.security import get_password_hash, verify_password
        from sqlalchemy import func
        import bcrypt
        print(f"[OK]   bcrypt version: {bcrypt.__version__}")
    except Exception as e:
        print(f"[FAIL] Import error: {e}")
        sys.exit(1)

    # Generate a fresh hash using this runtime's bcrypt
    new_hash = get_password_hash(DEMO_PASSWORD)
    is_valid = verify_password(DEMO_PASSWORD, new_hash)
    if not is_valid:
        print("[FAIL] bcrypt round-trip failed on this system. Cannot fix passwords safely.")
        sys.exit(1)
    print(f"[OK]   Fresh bcrypt hash generated and verified (length: {len(new_hash)})")

    db = SessionLocal()
    try:
        # Fix customers
        print(f"\n[*] Fixing {len(SEEDED_CUSTOMER_EMAILS)} customer password hashes...")
        cust_fixed = 0
        cust_missing = 0
        for email in SEEDED_CUSTOMER_EMAILS:
            c = db.query(CustomerData).filter(
                func.lower(CustomerData.email) == email.lower()
            ).first()
            if c:
                c.password_hash = new_hash
                cust_fixed += 1
            else:
                print(f"  [WARN] Customer not found: {email}")
                cust_missing += 1

        # Fix workers
        print(f"[*] Fixing {len(SEEDED_WORKER_EMAILS)} worker password hashes...")
        work_fixed = 0
        work_missing = 0
        for email in SEEDED_WORKER_EMAILS:
            w = db.query(WorkerData).filter(
                func.lower(WorkerData.email) == email.lower()
            ).first()
            if w:
                w.password_hash = new_hash
                work_fixed += 1
            else:
                print(f"  [WARN] Worker not found: {email}")
                work_missing += 1

        db.commit()

        print(f"\n[OK]   Customers fixed: {cust_fixed} ({cust_missing} missing)")
        print(f"[OK]   Workers fixed:   {work_fixed} ({work_missing} missing)")

        # Verify the demo accounts
        print("\n[*] Verifying demo accounts...")
        c = db.query(CustomerData).filter(
            func.lower(CustomerData.email) == "customer@example.com"
        ).first()
        if c:
            ok = verify_password(DEMO_PASSWORD, c.password_hash or "")
            print(f"  customer@example.com — verify: {ok}")
        w = db.query(WorkerData).filter(
            func.lower(WorkerData.email) == "worker@example.com"
        ).first()
        if w:
            ok = verify_password(DEMO_PASSWORD, w.password_hash or "")
            print(f"  worker@example.com   — verify: {ok}")

        print()
        print("=" * 58)
        print("[SUCCESS] Password fix complete. Deploy and test login.")
        print("=" * 58)

    except Exception as e:
        db.rollback()
        print(f"[FAIL] Database error: {e}")
        sys.exit(1)
    finally:
        db.close()


if __name__ == "__main__":
    main()
